env:
  TZ: "Asia/Jakarta"
  GITHUB_EMAIL: ENCRYPTED[8d081e946424a5e0ccd13e007d257161d0ca52dadf8df55cd9642fd3fb9e2275b9d56f2c1274254004d48bcdaaf47627]
  GITHUB_TOKEN: ENCRYPTED[029d9d8a02543ecf54d85f6b6990387a102735e1d5ffa57e751132013a8d2c74c99777a3b8f2a95e27dc0b81881eb625]
  GITHUB_USER: ENCRYPTED[80993a0149b3479d04f856d6334f7960e01ced280bcce7d0db1022bbec581a9122b6227638fed6cceafae33e095db87c]

container:
  image: mhmmdfdlyas/dockerfile:t-ubuntu
  cpu: 8
  memory: 32G

_build_toolchain_task: &build_toolchain_task
  skip: "!changesInclude('build-datestamp')"
  timeout_in: 120m
  only_if: $CIRRUS_BRANCH == 'main'
  script:
    - |
      for var in REPO WORKDIR ARCH TRIPLE; do
          [[ -z "${!var}" ]] && exit 0
      done
      git config --global user.name "$GITHUB_USER"
      git config --global user.email "$GITHUB_EMAIL"
      mkdir -p ~/.git/hooks
      git config --global core.hooksPath ~/.git/hooks
      curl -fsSL -o ~/.git/hooks/commit-msg https://review.lineageos.org/tools/hooks/commit-msg
      chmod u+x ~/.git/hooks/commit-msg
      git clone "https://${GITHUB_TOKEN}@github.com/greenforce-project/${REPO}" -b main "${WORKDIR}" --depth=1
      bash build-gcc.sh -a "${ARCH}"
      script_dir="$(pwd)"
      cd "${WORKDIR}"
      "./bin/${TRIPLE}-gcc" -v 2>&1 | tee ../gcc-version
      "./bin/${TRIPLE}-ld"  -v 2>&1 | tee ../ld-version
      bash "${script_dir}/strip-binaries.sh"
      build_tag="$(cat /tmp/gcc_date)"
      build_date="$(date +'%-d %B %Y')"
      git add . -f
      touch ../git_commit
      {
        echo "GCC version: $(grep 'gcc version' ../gcc-version)"
        echo "Binutils version: $(head -n1 ../ld-version)"
        echo "GCC repo commit: $(cat /tmp/gcc_commit)"
        echo "Link: https://github.com/gcc-mirror/gcc/commit/$(cat /tmp/gcc_hash)"
      } > ../git_commit
      git commit -m "greenforce: Bump to ${build_tag} build" -m "$(cat ../git_commit)" -s
      git push -f
      gcc_version="$(grep 'gcc version' ../gcc-version | awk '{for(i=1;i<=NF;i++) if ($i ~ /[0-9]+\.[0-9]+\.[0-9]+/) print $i}')"
      release_file="greenforce-GCC-${gcc_version}-${ARCH}-${build_tag}.tar.zst"
      tar -I 'zstd --ultra -5 -T0' -cf "${release_file}" ./*
      if gh release view "${build_tag}"; then
        gh release upload --clobber "${build_tag}" "${release_file}"
      else
        gh release create "${build_tag}" "${release_file}" -t "${build_date}"
      fi

build_arm64_tc_task:
  <<: *build_toolchain_task
  name: "Build ARM64 Toolchain"
  env:
    REPO: "gcc-arm64"
    WORKDIR: "gcc-arm64gnu"
    ARCH: "arm64gnu"
    TRIPLE: "aarch64-linux-gnu"

build_arm_tc_task:
  <<: *build_toolchain_task
  name: "Build ARM Toolchain"
  env:
    REPO: "gcc-arm"
    WORKDIR: "gcc-armgnu"
    ARCH: "armgnu"
    TRIPLE: "arm-linux-gnueabi"
